# Generated by Django 3.0.3 on 2020-02-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200221_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='title',
        ),
    ]
