# Generated by Django 3.0.3 on 2020-02-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200221_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='data',
            name='x',
            field=models.IntegerField(verbose_name='x data'),
        ),
        migrations.AlterField(
            model_name='data',
            name='y',
            field=models.IntegerField(verbose_name='y data'),
        ),
    ]
