# Generated by Django 3.0.3 on 2020-02-24 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200221_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('about', models.TextField(verbose_name='site description')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('project_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Programming Language',
            },
        ),
        migrations.CreateModel(
            name='ProjectsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('content', models.TextField(verbose_name='brief description')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.ProgrammingLanguage', verbose_name='Language')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(verbose_name='brief description')),
                ('published', models.DateTimeField(default=datetime.datetime.now, verbose_name='date completed')),
                ('project_slug', models.CharField(default=1, max_length=200)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.ProjectsCategory', verbose_name='project')),
            ],
        ),
    ]
