# Generated by Django 3.0.3 on 2020-02-24 06:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_about_programminglanguage_projectscategory_projectsinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemScrape',
            new_name='ItemsToScrape',
        ),
        migrations.RenameModel(
            old_name='ProjectsInfo',
            new_name='ProjectsContent',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Site content / About'},
        ),
        migrations.AlterModelOptions(
            name='itemstoscrape',
            options={'verbose_name_plural': 'Items To Scrape'},
        ),
        migrations.AlterModelOptions(
            name='projectscontent',
            options={'verbose_name_plural': 'content of projects'},
        ),
    ]
