# Generated by Django 3.0.3 on 2020-02-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200224_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Section'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='email',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='about',
            name='projects',
            field=models.TextField(default=1, verbose_name='github URLS'),
            preserve_default=False,
        ),
    ]
