# Generated by Django 3.0.3 on 2020-02-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200227_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=200)),
                ('libraries', models.TextField(verbose_name='libraries')),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.About', verbose_name='about lang')),
            ],
        ),
    ]
