# Generated by Django 3.0.3 on 2020-02-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200227_0514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Role'},
        ),
        migrations.RemoveField(
            model_name='aboutlanguage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutlanguage',
            name='projects',
        ),
        migrations.CreateModel(
            name='AboutProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Description')),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.About', verbose_name='about projects')),
            ],
        ),
    ]
