# Generated by Django 3.0.3 on 2020-02-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200227_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutprojects',
            name='role',
        ),
        migrations.AddField(
            model_name='about',
            name='languages',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='libraries',
            field=models.TextField(default=1, verbose_name='libraries'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AboutLanguage',
        ),
        migrations.DeleteModel(
            name='AboutProjects',
        ),
    ]
