# Generated by Django 3.0.3 on 2020-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200227_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='brief description')),
                ('libraries', models.TextField(verbose_name='Libraries used:')),
                ('language', models.CharField(default=1, max_length=200)),
                ('language_slug', models.CharField(default=1, max_length=200)),
                ('slug', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webapp', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='brief description')),
                ('languages', models.CharField(max_length=200)),
                ('libraries', models.TextField(verbose_name='Libraries used')),
                ('language_slug', models.CharField(default=1, max_length=200)),
                ('slug', models.CharField(default=1, max_length=200)),
            ],
        ),
    ]
