# Generated by Django 3.0.3 on 2020-04-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_uploadfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFile',
            new_name='FileUpload',
        ),
    ]
