# Generated by Django 3.0.3 on 2020-04-10 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200410_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='assets/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
