# Generated by Django 3.0.3 on 2020-04-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200410_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
