# Generated by Django 3.0.3 on 2020-04-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200410_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectscategory',
            name='language',
        ),
        migrations.RemoveField(
            model_name='projectscontent',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProgrammingLanguage',
        ),
        migrations.DeleteModel(
            name='ProjectsCategory',
        ),
        migrations.DeleteModel(
            name='ProjectsContent',
        ),
    ]
