version: "3"
services:
    django:
        build:
            context: .
            dockerfile: django.dev.Dockerfile
        volumes:
        - .:/neetcode/
        ports:
        - "8000:8000"
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    webpack:
        build:
            context: .
            dockerfile: node.Dockerfile
        volumes:
            - .:/neetcode/
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    
