version: "3"
services:
    django:
        build:
            context: .
            dockerfile: django.Dockerfile
        volumes:
        - .:/neetcode/
        ports:
        - "8000:8000"
    webpack:
        build:
            context: .
            dockerfile: node.Dockerfile
        volumes:
            -.:/neetcode/