version: "3"
services:
    django:
        build:
            context: .
            dockerfile: django.prod.Dockerfile
        volumes:
        - .:/neetcode/
        ports:
        - "8000:8000"
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    nginx:
        build:
            context: .
            dockerfile: nginx.dev.Dockerfile
        ports:
            - 1337:80
        depends_on: 
            - django
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    